<?php $this->headTitle()->set($this->te('Tests')); ?>
<div class="container-fluid test-definitions">
    <div class="row-fluid">
        <div class="nav-tabs-toolbar toolbar">
            <div class="input-prepend input-append search">
                <span class="add-on"><i class="icon-search"></i></span>
                <input class="input-large" name="keywords" type="text" placeholder="<?php echo $this->te('Search'); ?>">
                <button class="btn btn-search" type="button"><?php echo $this->te('Search'); ?></button>
            </div>
            <button id="add-test-definition-button" type="button" class="btn btn-add btn-lg privileged" data-toggle="modal" data-target="#test-definition-modal-content">
                <i class="icon-plus"></i><?php echo $this->te('Add Test Definition'); ?>
            </button>
        </div>
        <ul class="nav nav-tabs">
            <li class="tab active">
                <a id="my-test-definitions-tab" href="#my-test-definitions" data-toggle="tab"><?php echo $this->te('My Test Definitions'); ?></a>
            </li>
            <li class="tab">
                <a id="all-test-definitions-tab" href="#all-test-definitions" data-toggle="tab"><?php echo $this->te('All Test Definitions'); ?></a>
            </li>
        </ul>
    </div>
    <div class="row-fluid">
        <div class="tab-content">
            <div id="my-test-definitions" class="tab-pane active">
                <div class="test-definition-cells">
                </div>
            </div>
            <div id="all-test-definitions" class="tab-pane">
                <div class="test-definition-cells">
                </div>
            </div>
        </div>
    </div>
    <div id="test-definition-modal-content" class="modal hide fade add-test-definition" tabindex="-1" role="dialog" aria-labelledby="test-definition-content-title" aria-hidden="false"></div>
</div>
<script>$('document').ready(function(){
        swarm.testdefinition.init();
    });
</script>