<?php $this->headTitle()->set($this->te('Workflows')); ?>
<div class="messages alert border-box hidden"></div><div class="container-fluid workflows"><div class="busy-cover"></div>
    <div class="row-fluid">
        <div class="nav-tabs-toolbar toolbar">
            <div class="input-prepend input-append search">
                <span class="add-on"><i class="icon-search"></i></span>
                <input class="input-large" name="keywords" type="text" placeholder="<?php echo $this->te('Search'); ?>">
                <button class="btn btn-search" type="button"><?php echo $this->te('Search'); ?></button>
            </div>
            <button id="add-workflow-button" type="button" class="btn btn-add btn-lg privileged" data-toggle="modal" data-target="#workflow-modal-content">
                <i class="icon-plus"></i><?php echo $this->te('Add Workflow'); ?>
            </button>
        </div>
        <ul class="nav nav-tabs">
            <li class="tab active">
                <a id="my-workflows-tab" href="#my-workflows" data-toggle="tab"><?php echo $this->te('My Workflows'); ?></a>
            </li>
            <li class="tab">
                <a id="all-workflows-tab" href="#all-workflows" data-toggle="tab"><?php echo $this->te('All Workflows'); ?></a>
            </li>
        </ul>
    </div>
    <div class="row-fluid">
        <div class="tab-content">
            <div id="my-workflows" class="tab-pane active">
                <div class="workflow-cells">
                </div>
            </div>
            <div id="all-workflows" class="tab-pane">
                <div class="workflow-cells">
                </div>
            </div>
        </div>
    </div>
    <div id="workflow-modal-content" class="modal hide fade add-workflow" tabindex="-1" role="dialog" aria-labelledby="workflow-content-title" aria-hidden="false"></div>
</div>
<?php
use Application\Config\Services;
use Application\Permissions\Exception\ForbiddenException;
$workflowManager = $this->getHelperPluginManager()->get('serviceContainer')->getServices()->get(Services::WORKFLOW_MANAGER);
$globalWorkflow = [];
try {
    $globalWorkflow = $workflowManager->getGlobalWorkflow()->toArray();
} catch (ForbiddenException $fe ) {
    // Allow the error handling for the api call to get all workflow to deal with workflows being disabled
}
?>
<script>$('document').ready(function(){
    swarm.workflow.defaults = <?php echo json_encode($globalWorkflow); ?>;
    swarm.workflow.init();
});
</script>