<?php echo $this->doctype();?>
<html lang="en">
<head>
    <meta charset="UTF-8" />
<?php
    $services       = $this->getHelperPluginManager()->get('serviceContainer')->getServices();
    $translator     = $services->get('translator');
    $locale         = $translator->getLocale();
    $fallbackLocale = $translator->getFallbackLocale();

    // meta tags
    echo $this->headMeta()
        ->appendHttpEquiv('content-type', 'text/html; charset=utf-8')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=Edge')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0');

    // output title
    $this->headTitle()
        ->setSeparator(' - ')
        ->prepend('Swarm');
    echo $this->headTitle();

    // we extend the head link and head script helpers to add in our default css/scripts automatically
    // we will also include anything under public/custom/*.(js|css) or public/custom/*/*.(js|css)

    // link tags (icons, stylesheets)
    $this->headLink(['rel' => 'shortcut icon', 'href' => $this->assetBasePath() . '/favicon.ico?v3']);
    echo $this->headLink();

    // javascript
    $initTranslator = 'swarm.translator.init(' . json_encode($locale) . ', ' . json_encode($fallbackLocale) . ');';
    echo $this->headScript()
        ->addConfiguredScripts()
        ->addLanguageScripts($locale, $fallbackLocale)
        ->addCustomScripts()
        ->appendScript($initTranslator);
    ?>
</head>
<body>
<div id="react-container"></div>
<p type="text/javascript" src="public/assets/bundle.js"></p>
</body>
</html>