<?php
$this->headTitle()->set($this->te('Projects'));
?>
<div class="projects" data-maximum="<?php echo $maximum;?>">
    <!-- toolbar cannot be created in a js template as it needs to be in place when swarm.projects.init() is called -->
    <div class="toolbar">
        <div class="input-prepend input-append search">
            <span class="add-on"><i class="icon-search"></i></span>
            <input class="input-large" name="keywords" type="text" placeholder="<?php echo $this->te('Search'); ?>" value="<?php echo $keywords?>">
            <button class="btn btn-search" type="button"><?php echo $this->te('Search'); ?></button>
        </div>
        <a class="btn btn-add privileged project-add-restricted" href="<?php echo $this->url('add-project') ?>">
            <i class="icon-plus"></i><?php echo $this->te('Add Project'); ?>
        </a>
    </div>

    <ul class="nav nav-tabs">
        <li class="active">
            <a id="my-projects-tab" href="#my-projects" data-toggle="tab"><?php echo $this->te('My Projects'); ?></a>
        </li>
        <li>
            <a id="all-projects-tab" href="#all-projects" data-toggle="tab"><?php echo $this->te('All Projects'); ?></a>
        </li>
    </ul>

    <div class="tab-content">
        <div id="my-projects" class="active tab-pane"><div class="loading animate"><span class="muted"><?php echo $this->t('Loading...');?></span><span class='little-bee'></span></div></div>
        <div id="all-projects" class="tab-pane"><div class="loading animate"><span class="muted"><?php echo $this->t('Loading...');?></span><span class='little-bee'></span></div></div>
    </div>
</div>

<script type="text/javascript">
    $(swarm.projects.init);
</script>


