<?php
$this->headTitle()->set($this->te('System Information'));
$baseUrl = $this->escapeFullUrl($this->assetBasePath());
?>

<h1 class="info-title">
    <?php echo $this->te('System Information') ?>
</h1>

<div class="info-content">
    <ul class="nav nav-tabs info-tabs">
        <li class="active">
            <a href="#perforce" data-toggle="tab">
                <i class="icon-folder-open"></i> <?php echo $this->te('Perforce') ?>
            </a>
        </li>
        <li>
            <a href="#log" data-toggle="tab">
                <i class="icon-folder-open"></i> <?php echo $this->te('Log') ?>
            </a>
        </li>
        <li>
            <a href="#phpinfo" data-toggle="tab">
                <i class="icon-folder-open"></i> <?php echo $this->te('PHP Info') ?>
            </a>
        </li>
        <li>
            <a href="#queueinfo" data-toggle="tab">
                <i class="icon-folder-open"></i> <?php echo $this->te('Queue Info') ?>
            </a>
        </li>
        <li>
            <a href="#cacheinfo" data-toggle="tab">
                <i class="icon-folder-open"></i> <?php echo $this->te('Cache Info') ?>
            </a>
        </li>
        <li class="pull-right">
            <div class="btn-group pad1 padw0 hidden">
                <a href="#" title="<?php echo $this->te('Refresh Log')?>" class="btn btn-small btn-refresh">
                    <i class="icon-refresh"></i> <?php echo $this->te('Refresh Log') ?>
                </a>
                <a href="<?php echo $this->url('log') ?>" title="<?php echo $this->te('Download Log')?>" class="btn btn-small">
                    <i class="icon-download-alt"></i> <?php echo $this->te('Download Log') ?>
                </a>
            </div>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane fade in active" id="perforce">
            <table class="table table-compact p4info">
                <tbody>
                  <?php foreach($p4info as $name => $value): ?>
                    <tr>
                    <td class="muted p4info-name"><?php echo $this->escapeHtml($this->wordify($name)) ?></td>
                    <td><?php echo $this->escapeHtml($value) ?></td>
                    </tr>
                  <?php endforeach ?>
                </tbody>
            </table>
        </div>
        <div class="tab-pane fade" id="log">
            <div class="swarmlog-latest">
                <table class="table table-compact latest-log-entries">
                    <thead>
                    <tr>
                        <th class="entry-time"><?php echo $this->te('Time') ?></th>
                        <th class="entry-severity"><?php echo $this->te('Severity') ?></th>
                        <th class="entry-message"><?php echo $this->te('Message') ?></th>
                    </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
        <div class="tab-pane fade" id="phpinfo">
            <iframe src="<?php echo $this->url('phpinfo') ?>" width="100%" frameborder="0" scrolling="no"></iframe>
        </div>
        <div class="tab-pane fade" id="queueinfo">
            <div class="swarm-queue">
                <div class="queue-information">
                    <div id="queuepleasewait"><?php echo $this->te('Please wait') . '...'?></div>
                    <table class="table table-striped">
                        <tbody id="queueinfotablebody"></tbody>
                    </table>
                </div>
                <div class="queue-worker">
                    <button class="btn btn-small btn-primary" id="startqueueworker"><?php echo $this->te('Start a Worker')?></button>
                    <button class="btn btn-small btn-primary" id="updatequeue"><?php echo $this->te('Refresh Tab')?></button>
                    <button class="btn btn-small btn-primary" id="showqueue"><?php echo $this->te('Show Task Queue')?></button>
                    <button class="btn btn-small btn-primary" id="startdebugqueueworker"><?php echo $this->te('Start a Temp Worker')?></button>
                </div>
                <div class="tasks-list" style="display: none;">
                    <div class="tasks-information">
                        <h2>Task Queue</h2>
                        <table class="table table-hover">
                            <tbody id="taskstablebody"></tbody>
                        </table>
                        <table class="table table-hover">
                            <tbody id="futuretaskstablebody"></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="cacheinfo">
            <div class="swarm-cache">
                <div class="pad2">
                    <?php echo $this->te('Use of the Verify buttons could impact performance. Please refer to the') . ' '?>
                    <a href="<?php echo $baseUrl ?>/docs/Content/Swarm/admin.system_information.html#Verify" target="_swarm_docs">
                        <?php echo $this->te('Cache Info')?>
                    </a>
                    <?php echo ' ' . $this->te('tab documentation before use') ?>
                </div>
                <div class="cache-information">
                    <div id="cache-please-wait"><?php echo $this->te('Please wait') . '...'?></div>
                    <table class="table table-striped">
                        <tbody id="cache-info-table-body"></tbody>
                    </table>
                </div>
                <div class="queue-worker">
                    <button class="btn btn-small btn-primary" title="<?php echo $this->te('Refresh Redis status')?>" id="refresh-table"><?php echo $this->te('Refresh Status')?></button>
                    <button class="btn btn-small btn-primary" title="<?php echo $this->te('Verify all Redis cache')?>" id="verify-all"><?php echo $this->te('Verify All')?></button>
                    <button class="btn btn-small btn-primary" title="<?php echo $this->te('Verify Redis users cache')?>" id="verify-user"><?php echo $this->te('Verify User')?></button>
                    <button class="btn btn-small btn-primary" title="<?php echo $this->te('Verify Redis groups cache')?>" id="verify-group"><?php echo $this->te('Verify Group')?></button>
                    <button class="btn btn-small btn-primary" title="<?php echo $this->te('Verify Redis projects cache')?>" id="verify-project"><?php echo $this->te('Verify Project')?></button>
                    <button class="btn btn-small btn-primary" title="<?php echo $this->te('Verify Redis workflow cache')?>" id="verify-workflow"><?php echo $this->te('Verify Workflow')?></button>
                    <button class="btn btn-small btn-primary" title="<?php echo $this->te('Reload the Swarm config.php file')?>" id="clear-config"><?php echo $this->te('Reload Configuration')?></button>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function() {
        swarm.info.init();
    });
</script>
